// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1bLko3GtWf6PsYNYi8coQ4o-2mXQM6n4',
    appId: '1:918654981707:web:b5c7dcf602599126701fce',
    messagingSenderId: '918654981707',
    projectId: 'fruit-hub-a04d7',
    authDomain: 'fruit-hub-a04d7.firebaseapp.com',
    storageBucket: 'fruit-hub-a04d7.firebasestorage.app',
    measurementId: 'G-DKT7PQXJB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ1EiNMPmHsuJnJpXCIyM4VilG3yJagpQ',
    appId: '1:918654981707:android:c5eb10d1e6a33b74701fce',
    messagingSenderId: '918654981707',
    projectId: 'fruit-hub-a04d7',
    storageBucket: 'fruit-hub-a04d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh-3mcPyAJU7uc-6nj4dxCbmzLNdLtywk',
    appId: '1:918654981707:ios:3729cba493b5d536701fce',
    messagingSenderId: '918654981707',
    projectId: 'fruit-hub-a04d7',
    storageBucket: 'fruit-hub-a04d7.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh-3mcPyAJU7uc-6nj4dxCbmzLNdLtywk',
    appId: '1:918654981707:ios:3729cba493b5d536701fce',
    messagingSenderId: '918654981707',
    projectId: 'fruit-hub-a04d7',
    storageBucket: 'fruit-hub-a04d7.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1bLko3GtWf6PsYNYi8coQ4o-2mXQM6n4',
    appId: '1:918654981707:web:9fd85270aa3925d6701fce',
    messagingSenderId: '918654981707',
    projectId: 'fruit-hub-a04d7',
    authDomain: 'fruit-hub-a04d7.firebaseapp.com',
    storageBucket: 'fruit-hub-a04d7.firebasestorage.app',
    measurementId: 'G-6Z9ZV62FEJ',
  );
}
